version: '3.4'

services:
    postgres_db:
        image: postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres   
        ports:
          - 5436:5432

    vuejs:
        image: alejandro1050/vuejs-front:1.0
        environment: 
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASS: 1234
            DB_HOST: 'postgres_database'
            DB_PORT: 5432
        ports: 
            - 8080:8080
        depends_on:
            - postgres_db
    net:
        image: alejandro1050/back-net:1.0
        environment: 
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASS: 1234
            DB_HOST: 'postgres_database'
            DB_PORT: 5432
        ports: 
                - 5000:5000
        depends_on:
                - postgres_db