apiVersion: v1
kind: Service
metadata:
    name: vuejs-deploy
    labels:
        app: vuejs-deploy
spec:
    type: NodePort
    selector:
        app: vuejs-deploy
    ports:
        - protocol: TCP
          nodePort: 30001
          port: 8888
          targetPort: 8080