apiVersion: v1
kind: Service
metadata:
    name: laravel-deploy
    labels:
        app: laravel-deploy
spec:
    selector:
        app: laravel-deploy
    ports:
        - protocol: TCP
          port: 5555
          targetPort: 5000